
default: info


help:
	less README.tjk

compile:
	javac -nowarn *.java

run:
	java MemoryManagement commands memory.conf

setup:
	./setUp

info:
	@echo ""
	@echo "Use 'make' with one argument:"
	@echo ""
	@echo "  make help"
	@echo "  make compile"
	@echo "  make run"
	@echo ""
